name: Ancestry
channels:
  - bioconda/label/cf201901
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - alsa-lib=1.2.3=h516909a_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - atk-1.0=2.36.0=h3371d22_4
  - attmap=0.13.0=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcftools=1.13=h3a49de5_0
  - bcrypt=3.2.0=py38h497a2fe_1
  - boost-cpp=1.74.0=h312852a_4
  - boto3=1.18.48=pyhd8ed1ab_0
  - botocore=1.21.48=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - cairocffi=1.2.0=pyhd8ed1ab_0
  - cairosvg=2.5.2=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h578d9bd_0
  - cffi=1.14.6=py38h3931269_1
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38h578d9bd_0
  - coincbc=2.10.5=hcee13e7_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - coloredlogs=15.0.1=py38h578d9bd_1
  - colormath=3.0.0=py_2
  - commonmark=0.9.1=py_0
  - conda=4.10.3=py38h578d9bd_2
  - conda-package-handling=1.7.3=py38h497a2fe_0
  - configargparse=1.5.2=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cssselect2=0.2.1=pyh9f0ad1d_1
  - curl=7.79.1=hea6ffbf_0
  - cutadapt=3.4=py38h4a8c8d9_1
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py38h497a2fe_2
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.4=pyhd8ed1ab_0
  - dnaio=0.5.2=py38h4a8c8d9_0
  - docutils=0.17.1=py38h578d9bd_0
  - dropbox=11.20.0=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - fastqc=0.11.9=hdfd78af_1
  - fftw=3.3.10=nompi_h74d3f13_101
  - filechunkio=1.8=py_2
  - filelock=3.3.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.27.1=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - ftputil=5.0.1=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_3
  - g-ir-build-tools=1.70.0=py38h69e1f0e_0
  - g-ir-host-tools=1.70.0=h601b988_0
  - gatk4=4.2.2.0=hdfd78af_1
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.19.8.1=h73d1719_1008
  - ghostscript=9.54.0=h9c3ff4c_1
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - gobject-introspection=1.70.0=py38h382169c_0
  - google-api-core=1.31.2=pyhd8ed1ab_0
  - google-api-python-client=2.28.0=pyhd8ed1ab_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - google-cloud-core=1.7.1=pyh6c4a22f_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.1.2=py38h8838a9a_0
  - google-resumable-media=2.0.2=pyh6c4a22f_0
  - googleapis-common-protos=1.53.0=py38h578d9bd_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.49.0=h85b4f2f_0
  - grpcio=1.38.1=py38hdd6454d_0
  - gsl=2.6=he838d99_2
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - harfbuzz=2.9.1=h83ec7ef_0
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - html5lib=1.1=pyh9f0ad1d_0
  - htslib=1.13=h9093b5e_0
  - httplib2=0.20.1=pyhd8ed1ab_0
  - humanfriendly=9.2=py38h578d9bd_1
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - imagemagick=7.0.11_14=pl5320hb118871_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - importlib_resources=5.2.2=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipython_genutils=0.2.0=py_1
  - isa-l=2.30.0=ha770c72_4
  - jbig=2.1=h7f98852_2003
  - jemalloc=5.2.1=h9c3ff4c_5
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_core=4.9.1=py38h578d9bd_0
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.19.2=hcc1bbae_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libarchive=3.5.2=hccf745f_1
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=11_linux64_openblas
  - libcrc32c=1.1.1=h9c3ff4c_2
  - libcurl=7.79.1=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgd=2.3.3=h6ad9fb6_0
  - libgfortran-ng=11.2.0=h69a702a_8
  - libgfortran5=11.2.0=h5c6108e_8
  - libgirepository=1.70.0=hb520f89_0
  - libglib=2.68.4=h174f98d_1
  - libgomp=11.2.0=h1d223b6_8
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_openblas
  - libnghttp2=1.43.0=h812cca2_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.18.0=h780b84a_1
  - librsvg=2.52.0=hc3c00ef_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.19=h780b84a_5
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.1=h3452ae3_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h72842e0_0
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - lzstring=1.0.4=py_1001
  - mamba=0.17.0=py38h2aa5da1_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - more-itertools=8.10.0=pyhd8ed1ab_0
  - multidict=5.1.0=py38h497a2fe_1
  - multiqc=1.11=pyhdfd78af_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncbi-ngs-sdk=2.11.1=hff44eed_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.6.3=pyhd8ed1ab_0
  - numpy=1.21.2=py38he2449b9_0
  - oauth2client=4.1.3=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.3.17=pthreads_h4748800_1
  - openjdk=8.0.302=h7f98852_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - orfipy=0.0.4=py38h8c62d01_0
  - ossuuid=1.6.2=hf484d3e_1000
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py38h43a58ef_0
  - pango=1.48.10=hb8ff022_1
  - paramiko=2.7.2=pyh9f0ad1d_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pbzip2=1.1.13=0
  - pcre=8.45=h9c3ff4c_0
  - peppy=0.31.1=pyhd8ed1ab_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-parent=0.236=pl526_1
  - perl-uri=1.76=pl526_0
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xsloader=0.24=pl526_0
  - picard=2.26.2=hdfd78af_0
  - pigz=2.6=h27826a3_0
  - pillow=8.3.2=py38h8e6f84c_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - plink=1.90b6.21=h779adbc_1
  - pluggy=1.0.0=py38h578d9bd_1
  - ply=3.11=py_1
  - prettytable=2.2.1=pyhd8ed1ab_0
  - protobuf=3.18.0=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.5.1=py38h578d9bd_0
  - py=1.10.0=pyhd3deb0d_0
  - pyahocorasick=1.4.0=py38h1e0a361_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycosat=0.6.3=py38h497a2fe_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pydyf=0.1.1=pyhd8ed1ab_0
  - pyfastx=0.8.4=py38h390ddb8_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pygraphviz=1.7=py38h0d738da_0
  - pynacl=1.4.0=py38h497a2fe_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyphen=0.11.0=pyhd8ed1ab_0
  - pyrpipe=0.0.5=py_0
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysam=0.16.0.1=py38hf7546f9_3
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.5=py38h578d9bd_0
  - python=3.8.12=hb7a2778_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-irodsclient=1.0.0=pyhd8ed1ab_0
  - python-isal=0.11.1=py38h497a2fe_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_1
  - r-base=3.2.2=0
  - ratelimiter=1.2.0=py_1002
  - readline=8.1=h46c0cb4_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.26.0=pyhd8ed1ab_0
  - rich=10.11.0=py38h578d9bd_0
  - rsa=4.7.2=pyh44b312d_0
  - ruamel_yaml=0.15.80=py38h497a2fe_1004
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - salmon=1.5.2=h84f40af_0
  - samtools=1.13=h8c37831_0
  - scipy=1.7.1=py38h56a6a73_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h578d9bd_2
  - simplejson=3.17.5=py38h497a2fe_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=6.10.0=hdfd78af_0
  - snakemake-minimal=6.10.0=pyhdfd78af_0
  - spectra=0.0.11=py_1
  - sqlite=3.36.0=h9cd32fc_2
  - sra-tools=2.11.0=pl5262h314213e_0
  - star=2.7.9a=h9ee0642_0
  - statsmodels=0.12.2=py38h6c62de6_0
  - stone=3.2.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - stringtie=2.1.7=h978d192_0
  - tabix=1.11=hdfd78af_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tbb=2020.2=h4bd325d_4
  - tinycss2=1.1.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toposort=1.7=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - trim-galore=0.6.7=hdfd78af_0
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - unicodedata2=13.0.0.post2=py38h1e0a361_1
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - weasyprint=53.3=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - wrapt=1.12.1=py38h497a2fe_3
  - xmlrunner=1.7.7=py_0
  - xopen=1.2.0=py38h578d9bd_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_2
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - joblib==1.0.1
    - scikit-learn==0.24.2
    - threadpoolctl==2.2.0
